#-------------------------------
# General Site Settings
baseURL = "https://earthtoolsmaker.org"
languageCode = "en-us"
title = "EarthToolsMaker"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
# paginate = 6

[pagination]
pagerSize = 6

[params]
  math = true
  logo = "/images/logos/etm-logo-text.png" # You can add own logo. For example "/images/logo.png".
  # logo_dark = "/images/logo.png"
  description = "Open Technology for Wildlife and the Planet"
  # color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.
  color_scheme = "light" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.


  #-------------------------------
  # Author Settings
  [params.author]
    author_name = "EarthToolsMaker"


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "tools"
    name = "Tools"
    url = "/tools/"
    weight = 3
    hasChildren = true

  # [[menu.main]]
  #   parent = "tools"
  #   name = "BioWatch"
  #   # url = "/tools/biowatch"
  #   url = "https://v0-biowatch-landing-page.vercel.app/"

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Spaces"
    url = "/spaces/"
    weight = 5

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 6

  [[menu.main]]
    name = "Donate"
    url = "/donate/"
    weight = 7

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 8

      # [[menu.main]]
      # parent = "Pages"
      # name = "Contact"
      # url = "/contact/"
      # weight = 1

      # [[menu.main]]
      # parent = "Pages"
      # name = "Elements"
      # url = "/elements/"
      # weight = 2

      # Footer Menu
      [[menu.footer]]
      name = "Home"
      url = "/"
      weight = 1

      [[menu.footer]]
      name = "About"
      url = "/about/"
      weight = 2

      [[menu.footer]]
      identifier = "tools"
      name = "Tools"
      url = "/tools/"
      weight = 3

      [[menu.footer]]
      name = "Projects"
      url = "/projects/"
      weight = 4

      [[menu.footer]]
      name = "Spaces"
      url = "/spaces/"
      weight = 5

      [[menu.footer]]
      name = "Blog"
      url = "/posts/"
      weight = 6

      [[menu.footer]]
      name = "Donate"
      url = "/donate/"
      weight = 7

      [[menu.footer]]
      name = "Sponsor"
      url = "/sponsor/"
      weight = 8

      [[menu.footer]]
      name = "Contact"
      url = "/contact/"
      weight = 9


  #-------------------------------
  # Social Settings
  [[params.social]]
    icon = "fa-brands fa-github"
    name = "Github"
    link = "https://github.com/earthtoolsmaker"

  [[params.social]]
    icon = "fa-brands fa-solid fa-face-smiling-hands"
    # icon = "fa-brands fa-twitter"
    image = "/images/social/hf.svg"
    name = "HuggingFace"
    link = "https://huggingface.co/earthtoolsmaker"

  # [[params.social]]
  #   icon = "fa-brands fa-twitter"
  #   name = "Twitter"
  #   link = "https://twitter.com"

  # [[params.social]]
  #   icon = "fa-brands fa-facebook"
  #   name = "Facebook"
  #   link = "https://facebook.com"

  # [[params.social]]
  #   icon = "fa-brands fa-pinterest"
  #   name = "Pinterest"
  #   link = "https://pinterest.com"

  # Example of adding a new link to the header and footer:
  # [[params.social]]
  #  icon = "fa-brands fa-youtube"
  #  name = "Youtube"
  #  link = "https://youtube.com"

  # Other icons can be found at https://fontawesome.com/icons


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero_title = "Open Technology for <span><i>wildlife + planet</i></span>" # Add the "span" tag to highlight text.
    hero_description = "Developing Open Source technology to address conservation and environmental challenges for wildlife and the planet."
    hero_image = "/images/pages/home/hero.jpg"
    hero_button_contact = "Get In Touch"
    hero_button_about = "About"


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = true

  [params.projects.completed]
    enable = true
    projects_title= "👨🏻‍💻 Completed Projects"
    limit = 6

  [params.projects.fundraising]
    enable = true
    projects_title= "😇 Looking for Funding"
    limit = 3


  #-------------------------------
  # Testimonials Section
  [params.testimonials]
    enable = true
    testimonial_title = "🙂 What Partners Say"

  [[params.testimonial_item]]
    name = "Mateo Lostanlen"
    image = "/images/testimonials/mateo_pyronear.png"
    logo = "/images/clients/pyronear/logo.png"
    designation = "Co-founder and CEO - Pyronear"
    link = "https://www.pyronear.org"
    content = "We absolutely love working with you. You are incredibly professional. They trained our latest model and achieved outstanding performance, setting a new benchmark. They also implemented the MLOps pipeline!"

  [[params.testimonial_item]]
    name = "Will Atlas"
    image = "/images/testimonials/will-atlas.jpg"
    logo = "/images/clients/wild_salmon_centre/logo.png"
    designation = "Salmon Watershed Scientist - Wild Salmon Center"
    link = "https://wildsalmoncenter.org/"
    content = "It has been an absolute pleasure working with you on SalmonVision. Your diverse skillset, ability to be forward thinking, and work with our team of collaborators was essential to the success of our project. We really couldn't have done it without you! I hope we can continue working together to improve and expand the tools offered by SalmonVision over the coming years."

  [[params.testimonial_item]]
    name = "Yohan Runhaar"
    image = "/images/testimonials/yohan-reefsupport.jpg"
    logo = "/images/clients/reefsupport/logo_without_text.png"
    designation = "CTO - ReefSupport"
    link = "https://reef.support"
    content = "I am very excited for what is ahead, there is so much potential in the work that's been done. Your hard work and passion have really shone through!"


  [[params.testimonial_item]]
    name = "Thijs Suijten"
    image = "/images/testimonials/thijs-hacktheplanet.jpg"
    logo = "/images/clients/hacktheplanet/logo_without_text.png"
    designation = "Co-founder & CTO - HackThePlanet"
    link = "https://www.hack-the-planet.io/"
    content = "They really helped us by training a YOLOv8 model for our system to prevent human-bear-conflicts. He thinks along well, knows what he is talking about and is a nice person to work with!"

  [[params.testimonial_item]]
    name = "Melanie Clapham"
    image = "/images/testimonials/melanie-bearid.jpg"
    logo = "/images/clients/bearid/logo_without_text.png"
    designation = "Director & Conservation Scientist - The BearID Project"
    link = "https://bearresearch.org/"
    content = "There is definitely a want and need from the conservation community to work with people like you, with your expertise, as the technical side to this type of development is often the barrier. "


  # [[params.testimonial_item]]
  #   name = "Hanna Franci"
  #   image = "https://via.placeholder.com/200x200"
  #   designation = "Product Designer"
  #   link = "https://facebook.com/"
  #   content = "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"


  #-------------------------------
  # Blog Section
  [params.blog]
    enable = true
    blog_title = "📚 Read Latest Posts"


  #-------------------------------
  # Tags Section
  [params.tags]
    enable = true
    tags_title = "✌️ Explore Topics"


  #-------------------------------
  # Newsletter Settings
  [params.mailchimp]
    enable = true
    mailchimp_title = "Get interesting news"
    # FIXME:
    mailchimp_identifier = "caillau.us22.list-manage.com/subscribe/post?u=d8421822b19ca15ee7e4b0a6d&amp;id=8f6a5abb56&amp;f_id=007ac1e1f0"
    # mailchimp_identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp_input_text = "Enter your email address"
    mailchimp_background_image = "/images/subscribe/background.jpg"


  #-------------------------------
  # Footer Settings
  [params.footer]
    # footer_description = "I’m Aaron, a creative Illustrator & Art Director based in San Francisco. I seek to push the limits of creativity to create high-engaging and memorable interactive experiences."
    footer_description = "Developing Open Source technology to address conservation and environmental challenges for wildlife and the planet."


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact_email = "mqkrynry" # Add your form_id

    # NOTE
    # Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = false
    disqusShortname = "anvodstudio-demo" # Add your shortname for Disqus Comment. For example anvodstudio-demo


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
